### ISSUE TITLE
Categories redesign

### ISSUE THREAD

**Issue by Keisir** [inkdropapp/api-docs#4]
Hi everyone,
as the API documentation is being updated, I would like to take the opportunity to propose a revision of the categories.

Currently there is one big category "Essential Classes" which contains pretty much all classes you need for plugin development (well, the name suggests it 😄). Currently it looks like the categorization will continue under a new name "Core Modules".
Personally, I don't find this very intuitive and I didn't find my way around very quickly in the beginning. 

So I would suggest to rethink and split the categories. For example, the pages for the "event-kit" library ("Composite Disposable", "Disposable" and "Emitter") could be moved to a separate section. This would allow for a clearer distinction. The same could be done with "Environment", etc.

If this suggestion meets with approval, I can create a proposal as a PR so we can discuss the details.

@craftzdog, what do you think? Is this something you would like to see in the documentation?

**Comment by craftzdog** [comment]
agree. The classes from the non-app-specific libraries would be nice to be in a separate category.
I'm open to your suggestion!

**Comment by craftzdog** [comment]
@Keisir Hi!
I think I've finished migrating all the pages and it's time to redesign the categories?

**Comment by Keisir** [comment]
Hey,
a few months have passed since my first proposal, and in that time I have experimented with different structures for the categories. However, none of these new structures felt right to me. I keep coming back to the search function - it's better and that alone makes it easier to find information.

I think that no further actions are needed.

**Comment by craftzdog** [comment]
got it! Thanks for taking care of it :) Closing it now
