### ISSUE TITLE
Wrong redirection

### ISSUE THREAD

**Issue by Keisir** [inkdropapp/api-docs#5]
Hey,
While looking at this documentation I noticed a bug that redirects you to a different page twice.

Info:
The error occurs on Windows with Google Chrome or Firefox. No browser extensions are installed.

Steps to reproduce the bug:
1. click on a link, it doesn't matter if it is an external web page or a page of this documentation.
2. after opening the page, use the back button to return to the previous page.
3. within a few seconds you will be redirected to the page you navigated back from.

![wrong-redirection](https://github.com/inkdropapp/api-docs/assets/100614278/1aeb79e8-d388-4bff-be5c-a4b93d7f54b4)

**Comment by craftzdog** [comment]
Hi Keisir,

Thanks for the report.
ahh that's because it uses `next/link` for external links. Just `a` should be used here.

culprit: https://github.com/inkdropapp/api-docs/blob/c1eaf439a09c8c11692a1b8f2bf803af4ab08bcb/src/components/mdx.jsx#L8
